// LOCALHOST ### GET http://localhost:8080/contacts ### GET http://localhost:8080/contacts/ ### GET http://localhost:8080/contacts/ ### GET http://localhost:8080/contacts/

// PRODUCTION Deploy ### GET https://cs341-project.herokuapp.com/ ### GET https://cs341-project.herokuapp.com/ ### GET https://cs341-project.herokuapp.com/ ### GET https://cs341-project.herokuapp.com/